version: "3"

services:
  php:
    build:
      context: ../php
      args:
        TIMEZONE: ${TIMEZONE}
        PHP_VERSION: ${PHP_VERSION}
        SERVER: ${SERVER}
    volumes:
      - ../../${WWW_PATH}:/var/www/html
    networks:
      - mention_app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
